
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: util
  finalizers: []
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: k8s/overlays/prod
    repoURL: https://github.com/Markram-WS/pi-util.git
    targetRevision: HEAD
  sources: []
  project: util



    # - repoURL: https://github.com/Markram-WS/tradingsystem-metaapi.git
    #   path: k8s/overlays/onada-xxxx
    #   targetRevision: HEAD



