apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: central-gateway
  namespace: default
spec:
  listeners:
  - hostname: argocd.pi
    port: 80
    protocol: HTTP
  - hostname: postgres.pi
    port: 5432
    protocol: HTTP
---
# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: app2-route
#   namespace: app2
# spec:
#   parentRefs:
#   - name: shared-gateway
#     namespace: gateway-central
#   rules:
#   - matches:
#     - path:
#         type: Prefix
#         value: / # เส้นทางที่กำหนดสำหรับ App2
#     backendRefs:
#     - name: app2-service
#       namespace: app2
#       port: 80 # Port ภายใน Service ของ App2


