apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: default
  labels:
    app: postgres
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: secret-postgres
          env:
            - name: POSTGRES_USER
              value: "admin"       
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: postgres-route
  namespace: default  # เปลี่ยน namespace ให้ตรงกับที่คุณต้องการ
spec:
  parentRefs:
  - name: central-gateway
    namespace: default
  rules:
  - matches:
    - path:
        type: PathPrefix  # เปลี่ยนจาก 'Prefix' เป็น 'PathPrefix'
        value: /
    backendRefs:
    - name: postgres-service
      namespace: default
      port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres  